'use strict'

export const DISCOVER_PHOTOS_FETCH = 'DISCOVER_PHOTOS_FETCH'
export const DISCOVER_TAGS_FETCH = 'DISCOVER_TAGS_FETCH'

export const FEED_FETCH = 'FEED_FETCH'

export const GROUP_FETCH = 'GROUP_FETCH'
export const GROUP_UPDATE = 'GROUP_UPDATE'

export const PHOTOGROUP_ADD = 'PHOTOGROUP_ADD'
export const PHOTOGROUP_REMOVE = 'PHOTOGROUP_REMOVE'

export const MODAL_CLOSE = 'MODAL_CLOSE'
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_INPUT = 'MODAL_INPUT'

export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE'
export const NOTIFICATION_INPUT = 'NOTIFICATION_INPUT'

export const PHOTO_FETCH = 'PHOTO_FETCH'
export const PHOTO_UPDATE = 'PHOTO_UPDATE'
export const PHOTO_SHARE = 'PHOTO_SHARE'
export const PHOTO_LIKE = 'PHOTO_LIKE'

export const SESSION_FETCH = 'SESSION_FETCH'
export const SESSION_LOGIN = 'SESSION_LOGIN'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
export const SESSION_REGISTER = 'SESSION_REGISTER'
export const SESSION_UPDATE = 'SESSION_UPDATE'

export const USER_FOLLOWERS_FETCH = 'USER_FOLLOWERS_FETCH'
export const USER_FOLLOWERS_FOLLOW = 'USER_FOLLOWERS_FOLLOW'

export const USER_FOLLOWEES_FETCH = 'USER_FOLLOWEES_FETCH'
export const USER_FOLLOWEES_FOLLOW = 'USER_FOLLOWEES_FOLLOW'

export const USER_GROUPS_FETCH = 'USER_GROUPS_FETCH'
export const USER_GROUPS_CREATE = 'USER_GROUPS_CREATE'
export const USER_GROUPS_REMOVE = 'USER_GROUPS_REMOVE'

export const USER_LIKES_FETCH = 'USER_LIKES_FETCH'

export const USER_PHOTOS_FETCH = 'USER_PHOTOS_FETCH'
export const USER_PHOTOS_UPLOAD = 'USER_PHOTOS_UPLOAD'
export const USER_PHOTOS_REMOVE = 'USER_PHOTOS_REMOVE'

export const USER_PROFILE_FETCH = 'USER_PROFILE_FETCH'
export const USER_PROFILE_FOLLOW = 'USER_PROFILE_FOLLOW'
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE'
